language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install msgpack-python coverage python-coveralls"
# command to run tests
script: nosetests --with-coverage --cover-package=mcl
# run coverage with coveralls
after_script:
  - coveralls
